---
title: "Entomology 2025"
output:
  pdf_document: default
  word_document: default
  html_document: default
date: "2025-05-21"
---



## Conference Section: Medical, Urban, and Veterinary Entomology
## Venue: Portland, Oregon, USA.
## Date: 9-12th November 2025


$$
Abstract
$$


*Anopheles stephensi* —- a primary urban malaria vector in South Asia and the Middle East—has over the past decade, slowly invaded Africa, a region already heavily burdened by high malaria transmission. *An. stephensi* displays behaviours such as outdoor resting and feeding, as well as container breeding that enables it to thrive in urban environments and to evade conventional vector control measures like insecticide-treated nets (ITNs) and indoor residual spraying (IRS). This distinct behaviour poses a serious threat to recent progress in malaria control and present new challenges, particularly in rapidly urbanising areas. To address this emerging challenge, the World Health Organisation and public health stakeholders are advocating for innovative control strategies. Gene drive technologies, capable of spreading genetic modifications through populations, offer a promising approach. Despite their potential, deployment is constrained by regulatory, ethical, and public acceptance hurdles. In this study, using a patch-based, spatio-temporal, individual-based simulation model, we explore a novel genetic intervention strategy to assess whether introducing a genetic load can impose a genetic Allee effect, capable of disrupting population establishment by exploiting demographic and ecological dynamics. Our findings aim to inform proactive, cost-effective containment strategies before the vector becomes widespread and entrenched.