---
title: "Mathematical description of the IBM"
output:
  pdf_document: default
  html_document: default
date: "2025-05-09"
header-includes: \usepackage{wasysym}
---

We develop a spatially-explicit individual-based model (IBM) in discrete space and time that simulates the population dynamics, life history, and genetics of a generic diploid insect (e.g. dipterans) across a network of metapopulations/patches connected by dispersal. The model incorporates key biological processes: mating/reproduction, growth/transition, survival, and dispersal. Simulations are undertaken on a daily time step (indexed by $t$). Within each patch (indexed by $j$), individuals (indexed by $i$) are explicitly represented and tracked according to their life stage (egg, larva, pupa, adult), sex (male or female, denoted $\male$, $\female$ respectively), viability status (alive or dead), and diploid genotype. Stochastic life-cycle processes are described below.

## Reproduction

Whether or not a female reproduces in a given time period ($R_{i(\female), j, t}$) depends upon a chain of events.  Each adult female can potentially mate with any adult male present in the patch, and this occurs with some probability $m$ given at least one adult male is present in the patch.  Whether this mating then goes on to the successful production of eggs is also probabilistic, and depends on the female acquiring a bloodmeal, which we treat as occurring with probability, $b$.  Thus:

$$
R_{i(\female),j,t} \sim \text{Bernoulli}(bm)
$$

For each reproducing female, the number of eggs/offspring produced per day is drawn from a Poisson distribution: 

$$
O_{i(\female), j, t} \sim \text{Poisson}(f R_{i(\female),j,t})
$$
where $f$ is the daily female fecundity.


## Stage Development

Transition or developmental growth ($D_{i(s),j,t}$) through the different stages $S$ of an individual ($i$) (i.e. egg → larva → pupa → adult) occurs according to a daily stage-specific $s$ transition probability. 

$$
D_{i(s),j,t} \sim\text{Bernoulli}(d_{(s)})
$$
where $s\in S$ and $S = {egg, larva, pupa, adult}$ 



## Survival

Survival is modelled daily for each individual. It is stage-specific and governed by both intrinsic and extrinsic factors. Intrinsic survival $V$ is the baseline probability $v$ that an individual in any a given location survives regardless of environmental influences and its stage-specific. 
$$
V_{i(s),j,t} \sim\text{Bernoulli}(v_{(s)})
$$
Whereas, survival based on external influences such as predation, resources limitation and competition, etc. is captured through density-dependent survival and temperature-adjusted survival as shown below. 
